//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Courses
{
	protected virtual int courId
	{
		get;
		set;
	}

	protected virtual string courNom
	{
		get;
		set;
	}

	protected virtual int courNbPartMax
	{
		get;
		set;
	}

	protected virtual int courDistance
	{
		get;
		set;
	}

	protected virtual string courLieu
	{
		get;
		set;
	}

	protected virtual DateTime courDate
	{
		get;
		set;
	}

	public virtual Resultats Resultats
	{
		get;
		set;
	}

	public Courses(string Nom, DateTime Date, int Distance, string Lieu, int NbPartMax)
	{
	}

}

