//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Resultats
{
	protected virtual int resId
	{
		get;
		set;
	}

	protected virtual int resDossard
	{
		get;
		set;
	}

	protected virtual TimeSpan resTemps
	{
		get;
		set;
	}

	protected virtual int partId
	{
		get;
		set;
	}

	protected virtual int courId
	{
		get;
		set;
	}

	public virtual Courses laCourse
	{
		get;
		set;
	}

	public virtual IEnumerable<Participants> lesParticipants
	{
		get;
		set;
	}

	public Resultats()
	{
	}

}

