//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Sponsors
{
	protected virtual int sponId
	{
		get;
		set;
	}

	protected virtual string sponNom
	{
		get;
		set;
	}

	public virtual IEnumerable<Participants> lesParticipants
	{
		get;
		set;
	}

	public Sponsors(string Nom)
	{
	}

}

