//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Utilisateurs
{
	protected virtual int utilId
	{
		get;
		set;
	}

	protected virtual string utilNom
	{
		get;
		set;
	}

	protected virtual string utilMdp
	{
		get;
		set;
	}

	protected virtual string utilLogin
	{
		get;
		set;
	}

	public Utilisateurs(string Nom, string Login, string Mdp)
	{
	}

}

